/*
 * @Author: zsmya
 * @Date: 2022-05-19 14:40:27
 * @LastEditors: zsmya
 * @LastEditTime: 2022-05-19 15:59:39
 * @FilePath: /three-effect/auto-imports.d.ts
 * @Description:
 * Copyright (c) 2022 by zsmya, All Rights Reserved.
 */
// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {}
export {}
