/*
 * @Author: zsmya
 * @Date: 2022-06-14 18:04:29
 * @LastEditors: zsmya
 * @LastEditTime: 2022-06-14 18:04:40
 * @FilePath: /effect/auto-imports.d.ts
 * @Description:
 * Copyright (c) 2022 by zsmya, All Rights Reserved.
 */
// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {}
export {}
