/*
 * @Author: zsmya
 * @Date: 2022-06-14 18:04:29
 * @LastEditors: zsmya
 * @LastEditTime: 2022-06-14 18:06:24
 * @FilePath: /effect/components.d.ts
 * @Description:
 * Copyright (c) 2022 by zsmya, All Rights Reserved.
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core"

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElCard: typeof import("element-plus/es")["ElCard"]
    ElCol: typeof import("element-plus/es")["ElCol"]
    ElDialog: typeof import("element-plus/es")["ElDialog"]
    ElRow: typeof import("element-plus/es")["ElRow"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
  }
}

export {}
